### ISSUE TITLE
Requested css changes

### ISSUE THREAD

**Issue by ana0** [bitspossessed/culturestake#118]
Hyte requested a series of css changes, which would likely benefit from being broken into smaller issues, but stashing for now here:

https://docs.google.com/spreadsheets/d/1IlQlTcfYuLuFbdeJ0G9hlMBlJhC57ipdNX1llpSMqVw/edit?ts=5f6b7e2f#gid=0

**Comment by critocrito** [comment]
@ana0 can you grant access to this google doc, or copy the contents here?

**Comment by ana0** [comment]
Yes! We *may* not have to do this task tho - I asked Andreas, who worked on culturestake v1, for an estimate for him to do it. He did all the css and much of the frontend set up for v1, and I think it might be faster for him to take these things on then us. I should hear back in the next days
