### ISSUE TITLE
Festivals online flag must be clicked once to create new festivals

### ISSUE THREAD

**Issue by critocrito** [bitspossessed/culturestake#141]
When creating a new festival the `online` boolean flag must be clicked once to be initialized to a boolean. Otherwise validation fails and the festival can't be created. 

![Screen Shot 2021-03-04 at 09 02 43](https://user-images.githubusercontent.com/29301569/109930841-00910080-7cc0-11eb-8cbc-d58aa46cdaca.png)

1. Create a new festival.
2. Fill out `title`, `subtitle`, `website` and `description`.
3. Click on `Save`. This will cause a validation error.
4. Click on the `online` checkbox to enable it, and click again to disable it.
5. Click on `Save` to create the festival.

@aeluteia

**Comment by aeluteia** [comment]
I have hopefully fixed this with this PR: https://github.com/bitspossessed/culturestake/pull/145
