### ISSUE TITLE
When creating artworks image credits are required even if no image is attached

### ISSUE THREAD

**Issue by critocrito** [bitspossessed/culturestake#142]
Image credits probably should be only required if I select actually an image (right now I can create an artwork without an image but not without image credits).

![Screen Shot 2021-03-04 at 09 23 57](https://user-images.githubusercontent.com/29301569/109933119-f8869000-7cc2-11eb-9cb6-b9c749ca438a.png)

1. Create a new artwork.
2. Fill in `title`, `subtitle`, `activity description`, `commission description`, `website` and `artist`.
3. Click on `Save`. The validation will fail because of the missing `image credits`.
4. Fill in the `image credits`.
5. Click `Save`. The artwork is successfully created.

Besides the validation error I noticed that the image credits are not part of the HTTP request to the backend.

**Comment by ana0** [comment]
@aeluteia is working on this already! So far in #139
