### ISSUE TITLE
Voteweights table inside AdminFestivalsEdit should contain a "view" button

### ISSUE THREAD

**Issue by ana0** [bitspossessed/culturestake#146]
Right now, there is no option to view the details, only delete. Also, deleting takes you to the main admin home page but should return you to the AdminFestivalsEdit page

**Comment by critocrito** [comment]
Clicking anywhere on the table row will trigger a delete. The delete also goes through but doesn't reload the voteweight table removing the deleted item.

refs #134

**Comment by aeluteia** [comment]
This is fixed here: https://github.com/bitspossessed/culturestake/pull/159
