### ISSUE TITLE
Integrate mailgun

### ISSUE THREAD

**Issue by ana0** [bitspossessed/culturestake#165]
Oops we actually have a mailgun account

**Comment by critocrito** [comment]
I started looking into this, unfortunately I don't have a clear recommendation myself. Things I would look for in an email sending service are:

- The ability to disable tracking pixels and link rewriting, and any other form of tracking.
- SMTP transport. HTTP APIs are proprietary and makes switching between services much harder.
- Pricing.

There are hundreds of email sending services. I looked at two for now. Here are my notes so far.

## [Mailgun](https://www.mailgun.com/)

Can send email using SMTP and an HTTP API. Can be used as a [SMTP relay](https://documentation.mailgun.com/en/latest/user_manual.html#smtp-protocol)

_Pricing_: Probably 3 months free and then 0.80$/1000 emails. From 50K emails/mo on we can switch to a plan costing 35$/month.

There is a [transport plugin](https://www.npmjs.com/package/nodemailer-mailgun-transport) for Nodemailer to use the HTTP API.

Email tracking is enabled as a default but can be turned off (at least per message, maybe also globally). Mailgun has the `o:tracking` option to disable link rewriting when using the HTTP API. It also supports the `X-Mailgun-track` header in SMTP mode to toggle any tracking features. I'm not sure how those two complement each other.

## [Sendgrid](https://sendgrid.com/)

Can send email using SMTP and an HTTP API.

_Pricing_: Free for 100 emails per day, after that 14.95$ per month for 50K emails/mo.

There is an old [transporter package](https://www.npmjs.com/package/nodemailer-sendgrid-transport) for Nodenmailer to use the HTTP API. 

Click and link tracking can be [disabled](https://sendgrid.com/docs/ui/account-and-settings/tracking/).
