### ISSUE TITLE
Transaction nonce management

### ISSUE THREAD

**Issue by ana0** [bitspossessed/culturestake#20]
The backend transaction dispatcher should also use the queue, and retry if it's not sent with a correct nonce

**Comment by adzialocha** [comment]
Could we do it similar to the Safe contracts here: https://github.com/gnosis/safe-contracts/blob/development/contracts/GnosisSafe.sol#L139?

Like keeping the nonce on-chain and counting up after every vote transaction?

**Comment by ana0** [comment]
This actually won't work for the same reason fetching the transaction count from the ethereum network won't - and it's because it won't return info about pending (valid but unmined) transactions (we have this problem with Circles rn actually)
