### ISSUE TITLE
Input email page copy changes

### ISSUE THREAD

**Issue by ana0** [bitspossessed/culturestake#225]
Button and I think header message changes

Vote instructions should also be added to this page, tho not shown in the diagram

![image](https://user-images.githubusercontent.com/6787392/125250096-28d7de00-e2f6-11eb-8469-66fcff952ae2.png)

**Comment by critocrito** [comment]
@ana0 I'm not sure which view this exactly is. Is this the `Invitations` view?

**Comment by ana0** [comment]
Yes, it is!
