### ISSUE TITLE
Properties should be unique in answers for artwork questions

### ISSUE THREAD

**Issue by ana0** [bitspossessed/culturestake#86]

**Comment by ana0** [comment]
Also does not show the preview of the title greyed out, it still shows the prompt

**Comment by adzialocha** [comment]
> Also does not show the preview of the title greyed out, it still shows the prompt

This was related to a wrong setup, see here: https://github.com/lazaruslabs/culturestake/issues/88

**Comment by aeluteia** [comment]
[pull-request:](https://github.com/bitspossessed/culturestake/pull/166)
