### ISSUE TITLE
DX on setup from scratch

### ISSUE THREAD

**Issue by patcon** [bitspossessed/culturestake#98]
Hey all --

Friend of @ana0's who came to test setup and see how things went :)

Haven't been into blockchain dev for awhile, so this is verrrry newbie starting :) Considering how little i know about eth, setup is going pretty well, though not totally 1-2-3. but never feeling stuck :)

Pls don't consider any of this complaining, as i totally understand that new setup is often quite painful. This actually seemed pretty great, compared to many solo project onboardings!

1. cloned repo
1. readme looked clear, so started there :)
1. looked for node version spec in package.json. none, so just used latest lts v14 with nvm. installed fine.
1. copied sample env as is, though skimmed
1. tried to run tests first without postgres, thinking it might be a safer start (unit tests?). didn't work, but complained about missing webpack-assets.json, which was unexpected
1. googling told me this had to do with https://github.com/ztoben/assets-webpack-plugin, so realized (duh) needed to run webpack first. ran `npm build` got past that error.
1. `npm run test` and hit expected postgres error. don't use local postgres (always use docker), so added a minimal docker-compose file for my postgres db. swapped domain for ip, since i run docker on a remote machine via `docker-machine`, not localhost.
1. migration/seed now works. yay!
1. tried `npm run test`, hit issue with ETHEREUM_NODE_ENDPOINT and ETHEREUM_NODE_ENDPOINT_WS missing. googled to realize prob needed some local blockchain dev stuff that wasn't mentioned in readme. looked up dev frameworks as hint, recalled truffle as tool, and saw it mentioned in package.json, so focussed on getting that installed for a bit. aborted that. looked through git logs/blames, finding references to RPC and metamask. went down metamask research path a bit, then briefly considered hosted eth node services, but wanted to keep local for easy spin-up. finally googled port and realized geth was appropriate.
1. tried to set up geth in docker-compose container using ethereum/go-client. hit memory issues with starting that. aborted.
1. went back to hosted node services. considered Infura and Alchemy. Settled on Alchemy (hoping no CC required, as i don't have one)
1. knew mainnet wasn't appropriate, but brief research aside into testnet types for creating my test node. chose Rinkeby, but was tempted by Ropsten (since closest to mainnet seemed pref)
1. got hosted node set up, copied urls into .env
1. tried `npm run test`, but failed due to postgres issues with docker-compose not quickly supporting mulitple dbs in a container. couldn't get it to seed test database, so just skipped testing and ran `npm start` again.
1. Success! working and serving from localhost:3000!

Anyhow, wanted to share. Not presuming I have any clear resolutions on this stuff (or that it's even needed), but happy to submit PRs if anything jumps out :)

Things that may have supported me:
- pointers on hosted eth nodes
- docker-compose options for postgres (very particular to my style of dev tho)
- order of first-time commands so webpack-assets.json is present from start
- support to ensure tests run early, for those who sanity-check dev env that way

Anyhow, y'all are awesome!

Time spent: maybe 1.5-2h

**Comment by patcon** [comment]
And this is what I see of app when I go to see if I did it right. Not sure if there's a way for a first-time spin-up to show more. Really curious what you all see in your local dev, and how I could see that too :)

<img width="1404" alt="Screen Shot 2021-01-29 at 11 08 45 AM" src="https://user-images.githubusercontent.com/305339/106298826-6520f180-6222-11eb-8e62-e65dd6f49ace.png">
<img width="1407" alt="Screen Shot 2021-01-29 at 11 08 52 AM" src="https://user-images.githubusercontent.com/305339/106298829-66521e80-6222-11eb-8692-f3e2d556678e.png">

**Comment by patcon** [comment]
ha! Found this in travis config when I came back to this later today ;)
https://github.com/bitspossessed/culturestake-provisioning

**Comment by adzialocha** [comment]
@patcon :rose: I'm glad you found your way! The setup is indeed not clear, we should add a small note in the `README.md` that one can use the `culturestake-provisioning` for setup and write an in-depth guide for setting it up manually.

**Comment by patcon** [comment]
Thanks! I'm happy to submit a PR once I definitely have something working.

Am I expecting that a full success will have some numbers besides zero on the frontpage?

**Comment by patcon** [comment]
Closing in light of: https://github.com/bitspossessed/culturestake/pull/99 Thanks!
